### ISSUE TITLE
Alternative name for project

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notpad#169]
Reasons:
1. May conflict with default notepad on windows
2. `notepad` is already taken for linux, (or with wine on linux)

**Comment by Brijeshthummar02** [comment]
can you explain it more so that i get clarity about issue.

**Comment by Muhammed-Rahif** [comment]
Changing project to name to something else. Eg: padnote

**Comment by Brijeshthummar02** [comment]
so like you wanted to change main Notepad name to some other name?

**Comment by Brijeshthummar02** [comment]
i can suggest some like WriteWise, QuickQuill, DocuMate, WritePad. so what you say?

**Comment by AaEnnDeeErrEeEss** [comment]
Package name and project name do not need to match. So that alone is not a reason to change the name of the project, in my opinion.
However it would be good to change it to avoid confusing it with the original.

**Comment by Brijeshthummar02** [comment]
now i'm confused do i have to change package name or project name or both ? suggest me everything, as i've forked the repo so i change it right now.

**Comment by AaEnnDeeErrEeEss** [comment]
My opinion is that the project name should be changed.
The package name should be both easy to remember, and easily relatable to the project name.

**Comment by AaEnnDeeErrEeEss** [comment]
NotPad
NetoPad
NtePad
NotePab
NotePd
And my favorite, **nÕtepad**

**Comment by Muhammed-Rahif** [comment]
I like the `Notpad`. @Brijeshthummar02 what do you think?

**Comment by Muhammed-Rahif** [comment]
Confirm on `notpad`. Please update your git remote url on local:
```bash
git remote set-url origin git@github.com:Muhammed-Rahif/Notpad.git
```
@shifnmalik @sinankambran

**Comment by Muhammed-Rahif** [comment]
Should update `Notepad` => `Notpad` throughout the project.

**Comment by Brijeshthummar02** [comment]
@Muhammed-Rahif sounds good, i'll updating it soon.

**Comment by Muhammed-Rahif** [comment]
Can't wait, the deployment is down.
