### ISSUE TITLE
Edit options

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notpad#175]
- [x] Undo and Redo
- [x] Cut, Copy and Paste
- [x] Select All and Insert Date
- [x] Font

**Comment by devrupchowdhury** [comment]
Hi, @Muhammed-Rahif  i would like to work on this issue please assign me this .

**Comment by Trishank7409** [comment]
i am working on this and soon i provide you completed code PR

**Comment by Muhammed-Rahif** [comment]
@Trishank7409 You should have asked to be assigned this problem before you even started working on it. Anyways looking forward to your PR.

**Comment by Shifin-Malik** [comment]
I can take responsibility for implementing the Select All and Insert Date functionality for the edit options.

**Comment by Muhammed-Rahif** [comment]
@Trishank7409 any updates?

**Comment by Trishank7409** [comment]
@Muhammed-Rahif  you can Check the PR. All Done!
Font and Select All is not implemented Ask to @Shifin-Malik  to do this . If not then i can try to do it

**Comment by Shifin-Malik** [comment]
I will do the “Select All” option. @Muhammed-Rahif said he will take care of “Font” feature.
