### ISSUE TITLE
Help options

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notpad#178]
- [x] About notpad

About should contain logo, contributors list(live), a small description, GitHub repo link, copyright declaration and other licensed items used (eg. SUSE font family)

**Comment by sinankambran** [comment]
can i take
![Image 2024-09-30 at 8 18 19 AM](https://github.com/user-attachments/assets/a157c7dd-de78-4898-9e5b-25028df831f7)

**Comment by sinankambran** [comment]
Can I Take

**Comment by sinankambran** [comment]
Can I take the issue

**Comment by sinankambran** [comment]
Can I take this issue

**Comment by Muhammed-Rahif** [comment]
Please add a screenshot from original windows notepad, so that I can give you instructions.

**Comment by sinankambran** [comment]
![Image 2024-09-30 at 8 18 19 AM](https://github.com/user-attachments/assets/d8965ed8-f758-4354-92c4-a6373cbe5991)

**Comment by SanidhyaSharma28** [comment]
can i give it a try can you assign it to me if no one's working on it?

**Comment by Muhammed-Rahif** [comment]
Resolved #204.
