### ISSUE TITLE
Zoom in/out/reset feature

### ISSUE THREAD

**Issue by rahulpeacock** [Muhammed-Rahif/Notpad#185]
I would like to work on the zoom in/zoom out feature similar to notepad 

![image](https://github.com/user-attachments/assets/a664b0d1-cece-4fee-91ac-ac10569a33b0)

Please assign this issue to me

**Comment by rahulpeacock** [comment]
@Muhammed-Rahif sorry I thought the codebase is in react but it is in svelte,

I cannot solve this issue

**Comment by Muhammed-Rahif** [comment]
No worries.

**Comment by Muhammed-Rahif** [comment]
Closing. Moved to https://github.com/Muhammed-Rahif/Notpad/issues/177#:~:text=Zoom%20in%2C%20out%20and%20reset
