### ISSUE TITLE
Add Dark mode and light mode in the code and improve css quality

### ISSUE THREAD

**Issue by ankit071105** [Muhammed-Rahif/Notpad#186]
Add Dark mode and light mode in the code and improve css quality of code . adding responsive webpage features

**Comment by Muhammed-Rahif** [comment]
Please explain more. Dark/light mode is already done. And I don't see any problem with responsiveness. And you are always welcome to improve the quality of code :smile:.

**Comment by ankit071105** [comment]
> Please explain more. Dark/light mode is already done. And I don't see any problem with responsiveness. And you are always welcome to improve the quality of code 😄.

I want to align all the nav bar items to center give them some box shadow border and background color.

**Comment by ankit071105** [comment]
> Aligning menu bar contents to the center will make it worse and will cause to lose the similarity of original windows notepad.
> 
> Can you share a sample screenshot of it by editing styles through developer tools so that can understand what you are meant.

okay
