### ISSUE TITLE
Feature Request: Add Character Count to Notepad

### ISSUE THREAD

**Issue by masabinhok** [Muhammed-Rahif/Notpad#189]
### Feature Request: Add Character Count Feature to Notepad

**Description:**
The current version of the Notepad application is missing a character count feature, which is a useful addition for users who need to track the number of characters while writing. Adding a live character count display can enhance the user experience, especially for tasks like writing within a character limit (e.g., tweets, text fields).

**Feature Requirements:**
- Display the total number of characters in the document, updated in real-time as the user types.
- Include the character count in a status bar or a dedicated section within the UI.
- The count should update dynamically when characters are added, deleted, or modified.
- Ensure the feature works for all text input cases, including pasting text.
- Consider excluding spaces and newlines from the count if applicable (optional feature toggle).

**Additional Notes:**
- The character count should be displayed at all times for ease of access.
- Keep the UI design minimalistic and consistent with the current Notepad layout.
- Follow the existing coding conventions and structure of the project.

### Priority: Medium  
This feature is not critical, but it would greatly improve the functionality and usability of the Notepad application.

**Comment by masabinhok** [comment]
Hi, I noticed that this feature is missing and would love to work on it. Could you please assign this issue to me? Thanks!

**Comment by Muhammed-Rahif** [comment]
Fixed by https://github.com/Muhammed-Rahif/Notpad/pull/192
