### ISSUE TITLE
Adaptive height when keyboard is visible on mobile devices

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notpad#207]

**Comment by TechGeekRahul** [comment]
hi @Muhammed-Rahif I want to work on this issue.can you assign it to me ?

**Comment by Muhammed-Rahif** [comment]
[Get viewport height when soft keyboard is on](https://stackoverflow.com/questions/23023549/get-viewport-height-when-soft-keyboard-is-on)

**Comment by sinankambran** [comment]
hey @Muhammed-Rahif I want to work on this issue.can you assign it to me?

**Comment by Muhammed-Rahif** [comment]
resolved in #229
