### ISSUE TITLE
Loading animation

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notpad#209]

**Comment by TechGeekRahul** [comment]
hey @Muhammed-Rahif  I want to work on this issue.can you assign it to me?

**Comment by Muhammed-Rahif** [comment]
FYI: https://svelte.dev/examples/await-blocks

**Comment by Shifin-Malik** [comment]
hey @Muhammed-Rahi I can take on implementing the loading animation. Can you assign it to me?

**Comment by Muhammed-Rahif** [comment]
resolved in #222
