### ISSUE TITLE
Help Option > Add a New Button: "Display All Shortcuts"

### ISSUE THREAD

**Issue by Shifin-Malik** [Muhammed-Rahif/Notpad#227]
Expected Behavior   
1. The Help > A new button: "Display All Shortcuts".  
2. When the button is clicked:  
   - A modal/pop-up is displayed.  
   - The modal contains a comprehensive list of all shortcuts available in the application.  
   - The shortcuts are displayed in a user-friendly format, such as a table or list.

**Comment by Muhammed-Rahif** [comment]
#238
