### ISSUE TITLE
Add SEO content to `<head>`

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notpad#231]

**Comment by Shifin-Malik** [comment]
hey @Muhammed-Rahif can you assign me to work on this issue?

**Comment by Shifin-Malik** [comment]
![photo_6271514583265034626_y](https://github.com/user-attachments/assets/872d0ba4-ebb0-40ab-82ab-3e9e07780bb1)

**Comment by Muhammed-Rahif** [comment]
Resolved #280
