### ISSUE TITLE
Allow editing editor file name length longer than currently available

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/Notpad#247]

**Comment by Ravi0529** [comment]
Hi @Muhammed-Rahif ,

Could you clarify your expectation?

Changing the maximum allowed length of the file name. If yes, then what should be the new length?
Allowing users to define their own maximum length?

**Comment by Ravi0529** [comment]
Okay then, I'll fork the repo and make the maxlength a bit higher.

**Comment by Ravi0529** [comment]
I have to send a pull request on main branch of your repo? or alpha?

**Comment by Muhammed-Rahif** [comment]
To alpha, see https://github.com/Muhammed-Rahif/Notpad/blob/main/CONTRIBUTING.md

**Comment by Muhammed-Rahif** [comment]
#252
