### ISSUE TITLE
[Feature] Add word counter

### ISSUE THREAD

**Issue by 4rnv** [Muhammed-Rahif/Notpad#248]
Hello, I really like your project!
I think adding a word counter would be a great idea. It would help users keep track of their word count, which is especially useful for writing essays or statements of purpose that often have specific word limits. Many types of formal writing require this. While MS Word has a built-in counter, Microsoft Notepad doesn’t. So it'll be an additional feature for Notpad when compared to Notepad.

**Comment by 4rnv** [comment]
Also if possible I'd like to work on this myself. Could you assign this to me?

**Comment by Muhammed-Rahif** [comment]
#249
